version: '3.8'

services:
  dtm:
    build: .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace
    working_dir: /workspace
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    command: analyze --format chart --output /workspace/report.html
