name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Install dependencies
      run: go mod download
    
    - name: Run tests
      run: go test -v ./...
    
    - name: Build
      run: go build -v ./...
    
    - name: Run DTM on this repo
      run: |
        go run main.go analyze --dockerfile Dockerfile \
          --max-commits 10 --format json > dtm-report.json
    
    - name: Upload report
      uses: actions/upload-artifact@v3
      with:
        name: dtm-report
        path: dtm-report.json
    
    - name: Check for size regression
      run: |
        SIZE=$(cat dtm-report.json | jq '.[].image_size' | tail -1)
        if [ "$SIZE" -gt "1000000000" ]; then
          echo "Image size exceeds 1GB!"
          exit 1
        fi

  release:
    needs: test
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
    
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v4
      with:
        distribution: goreleaser
        version: latest
        args: release --clean
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
